### ISSUE TITLE
range[T] can lead to ambiguous call

### ISSUE THREAD

**Issue by DylanModesitt** [treeform/flatty#22]
# `range[T]` can lead to ambiguous calls 

```
type
  Direction = enum North, South, East, West
  DirRange = range[North..West]
  RangeT = range[1..10]
  RangeU = range[1.0..10.0]
  Thing = object
    name: string
    X: RangeT
    Y: RangeU
    Z: DirRange

when isMainModule:
  let u = @[
    Thing(name: "hi", X: 1.RangeT, Y: 1.0.RangeU, Z: North.DirRange),
    Thing(name: "bye", X: 2.RangeT, Y: 2.0.RangeU, Z: West.DirRange)
  ]

  echo u
  let f = toFlatty[seq[Thing]](u)
  let u2 = fromFlatty(f, seq[Thing])
  echo u2
```

gives 

```
Error: ambiguous call; both flatty.toFlatty(s: var string, x: int8) [declared in /Users/dcm/.nimble/pkgs/flatty-0.2.1/flatty.nim(39, 6)] and flatty.toFlatty(s: var string, x: int32) [declared in /Users/dcm/.nimble/pkgs/flatty-0.2.1/flatty.nim(43, 6)] match for: (string, RangeT)
```

(on  `Nim Compiler Version 1.4.4 [MacOSX: amd64]`)

due to implicit conversions for range types. I will also note that similar types to `Thing`, like those that do not include `name`, actually do compile. Regardless, they could maybe be explicitly handled (with `enum` to avoid another ambiguous calls for `range`s on `enum`s):
```
proc toFlatty*[T: range|enum](s: var string, x: T) =
  when T is enum:
    s.addInt64(x.int)
    return
  when T is SomeFloat:
    s.toFlatty(float(x))
  when T is SomeOrdinal:
    s.toFlatty(int(x)
```

**Comment by JorySchossau** [comment]
This issue also affects attempts to serialize `DateTime` objects from the `times` module.

**Comment by treeform** [comment]
@DylanModesitt Hey thank you for the bug report! For some reason it slipped though. I have a fix for it though. See: https://github.com/treeform/flatty/commit/ab4b7fb1c25582b6095b6d7a7411e50d6b8ff1e7

@JorySchossau DateTime had a problem with range but it has bigger problem that it wants to serialize the whole attached timezone which contains code `proc (x: Time): ZonedTime`. Supporting DateTime is impossible without a custom hook. Checkout my chrono library which works: https://github.com/treeform/chrono or convert DateTime into Unix time stamp.
